CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgrouting;

-- Routing edge table built from OSM-derived geometry.
CREATE TABLE IF NOT EXISTS run_edges (
  id BIGSERIAL PRIMARY KEY,
  source BIGINT,
  target BIGINT,
  cost DOUBLE PRECISION NOT NULL,
  reverse_cost DOUBLE PRECISION NOT NULL,
  geom geometry(LineString, 4326) NOT NULL,
  length_m DOUBLE PRECISION NOT NULL,
  highway TEXT,
  surface TEXT
);

CREATE INDEX IF NOT EXISTS run_edges_geom_gix ON run_edges USING GIST (geom);
CREATE INDEX IF NOT EXISTS run_edges_source_idx ON run_edges (source);
CREATE INDEX IF NOT EXISTS run_edges_target_idx ON run_edges (target);

-- Vertex table generated by pgRouting topology process.
CREATE TABLE IF NOT EXISTS run_vertices (
  id BIGINT PRIMARY KEY,
  geom geometry(Point, 4326) NOT NULL
);

CREATE INDEX IF NOT EXISTS run_vertices_geom_gix ON run_vertices USING GIST (geom);

-- Example utility view for metric length in geography.
CREATE OR REPLACE VIEW run_edges_metrics AS
SELECT
  id,
  source,
  target,
  ST_Length(geom::geography) AS length_m,
  geom,
  highway,
  surface
FROM run_edges;
